name: RustLinux

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Config Env
        run: rustup install nightly && rustup default nightly && rustup component add rustfmt
      - name: Build
        run: cd gdrust && cargo build --all
      - name: Build Release
        run: cd gdrust && cargo build --all --release
      - name: Run tests Debug
        run: cd gdrust && cargo test --all
      - name: Run tests Release
        run: cd gdrust && cargo test --all --release
      - name: Check Fmt
        run: cd gdrust && cargo fmt -- --check
